FROM python:3.11.3-bullseye

RUN pip install "poetry==1.3.2"

WORKDIR /usr/src/app
COPY poetry.lock pyproject.toml .

RUN poetry config virtualenvs.create false \
  && poetry install --no-root --without dev --no-interaction --no-ansi

COPY . /usr/src/app

EXPOSE 3001

CMD ["flask", "run", "--host=0.0.0.0", "--port=3001", "--debug"]
